#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-2.1-or-later

import argparse
import os
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from enum import Enum

SCRIPT_DIRECTORY = os.path.dirname(os.path.abspath(__file__))

PROJECT_DIRECTORY = os.path.dirname(SCRIPT_DIRECTORY)

XR_XML = os.path.join(PROJECT_DIRECTORY, "extern", "OpenXR-SDK", "specification", "registry", "xr.xml")

INCLUDE_DIRECTORY = os.path.join(PROJECT_DIRECTORY, "src", "include")

UNIXCALL_H = os.path.join(INCLUDE_DIRECTORY, "unixcall.h")
DISPATCH_H = os.path.join(INCLUDE_DIRECTORY, "dispatch.h")
EXTENSIONS_H = os.path.join(INCLUDE_DIRECTORY, "extensions.h")
EVENTS_H = os.path.join(INCLUDE_DIRECTORY, "events.h")

PE_THUNKS_C = os.path.join(PROJECT_DIRECTORY, "src", "pe", "thunks.c")
UNIX_THUNKS_C = os.path.join(PROJECT_DIRECTORY, "src", "unix", "thunks.c")

GENERATED_BANNER = "/* Generated by make_openxr.py. Do not edit manually */"


class Emit(Enum):
    AUTO = "auto"
    MANUAL = "manual"
    SKIP = "skip"


AUTO, MANUAL, SKIP = Emit.AUTO, Emit.MANUAL, Emit.SKIP


@dataclass(frozen=True)
class ThunkPolicy:
    pe: Emit = AUTO
    unix: Emit = AUTO
    dispatch: bool = True
    extra_params: tuple = ()

    def __post_init__(self):
        if self.pe is SKIP and self.unix is not SKIP:
            raise RuntimeError("pe=SKIP requires unix=SKIP")
        if self.unix is SKIP and self.pe is AUTO:
            raise RuntimeError("unix=SKIP requires pe=MANUAL or pe=SKIP")
        if self.extra_params and (self.pe is SKIP or self.unix is SKIP):
            raise RuntimeError("extra_params requires a generated params struct")
        if not self.dispatch and self.unix is AUTO:
            raise RuntimeError("dispatch=False requires unix=MANUAL or unix=SKIP")

    @property
    def has_unix_call(self):
        return self.unix is not SKIP


FUNCTION_POLICIES = {
    "xrCreateInstance": ThunkPolicy(pe=MANUAL, unix=MANUAL, dispatch=False),
    "xrDestroyInstance": ThunkPolicy(pe=MANUAL, unix=MANUAL),
    "xrGetInstanceProcAddr": ThunkPolicy(pe=MANUAL, unix=SKIP, dispatch=False),
    "xrEnumerateInstanceExtensionProperties": ThunkPolicy(unix=MANUAL, dispatch=False),
    "xrEnumerateApiLayerProperties": ThunkPolicy(pe=MANUAL, unix=SKIP, dispatch=False),

    "xrCreateSession": ThunkPolicy(pe=MANUAL, unix=MANUAL),
    "xrDestroySession": ThunkPolicy(pe=MANUAL),
    "xrPollEvent": ThunkPolicy(pe=MANUAL),

    "xrCreateSwapchain": ThunkPolicy(pe=MANUAL, unix=MANUAL),
    "xrDestroySwapchain": ThunkPolicy(pe=MANUAL),
    "xrEnumerateSwapchainFormats": ThunkPolicy(unix=MANUAL),
    "xrEnumerateSwapchainImages": ThunkPolicy(pe=MANUAL),
    "xrReleaseSwapchainImage": ThunkPolicy(pe=MANUAL, unix=MANUAL, extra_params=("uint64_t gpu_fence_value;",)),
    "xrEndFrame": ThunkPolicy(pe=MANUAL, unix=MANUAL),

    "xrGetD3D11GraphicsRequirementsKHR": ThunkPolicy(pe=MANUAL, unix=MANUAL, dispatch=False),
    "xrGetD3D12GraphicsRequirementsKHR": ThunkPolicy(pe=MANUAL, unix=MANUAL, dispatch=False),
    "xrConvertTimeToWin32PerformanceCounterKHR": ThunkPolicy(pe=MANUAL, unix=MANUAL, dispatch=False),
    "xrConvertWin32PerformanceCounterToTimeKHR": ThunkPolicy(pe=MANUAL, unix=MANUAL, dispatch=False),

    "xrGetMetalGraphicsRequirementsKHR": ThunkPolicy(pe=SKIP, unix=SKIP),
    "xrConvertTimespecTimeToTimeKHR": ThunkPolicy(pe=SKIP, unix=SKIP),
    "xrConvertTimeToTimespecTimeKHR": ThunkPolicy(pe=SKIP, unix=SKIP),
}

SUPPORTED_EXTENSIONS = frozenset({
    "XR_KHR_D3D11_enable",
    "XR_KHR_D3D12_enable",
    "XR_KHR_win32_convert_performance_counter_time",
    "XR_KHR_visibility_mask",
    "XR_KHR_composition_layer_depth",
    "XR_KHR_locate_spaces",
    "XR_KHR_extended_struct_name_lengths",
    "XR_EXT_hand_tracking",
    "XR_FB_display_refresh_rate",
    "XR_META_performance_metrics",
    "XR_KHR_composition_layer_cylinder",
    "XR_KHR_composition_layer_equirect",
    "XR_KHR_composition_layer_equirect2",
    "XR_KHR_composition_layer_cube",
})

GLOBAL_FUNCTIONS = frozenset({
    "xrEnumerateInstanceExtensionProperties",
    "xrEnumerateApiLayerProperties",
    "xrCreateInstance",
})

CUSTOM_UNIX_CALLS = (
    "create_d3d11_session",
    "release_metal_session",
    "export_metal_textures",
    "dmsubst",
)

UNSUPPORTED_TYPES = frozenset({"wchar_t"})

STRIPPED_NEXT_CHAINS = frozenset({"XrInstanceCreateInfo"})

REGISTRY_SUPPORTED_REQUIRES = frozenset({
    "openxr_platform_defines",
    "d3dcommon.h",
    "d3d12.h",
    "windows.h",
})

D3D11_GUARD = "XR_USE_GRAPHICS_API_D3D11"
D3D12_GUARD = "XR_USE_GRAPHICS_API_D3D12"
METAL_GUARD = "XR_USE_GRAPHICS_API_METAL"
WIN32_GUARD = "XR_USE_PLATFORM_WIN32"
TIMESPEC_GUARD = "XR_USE_TIMESPEC"

PE_GUARDS = frozenset({None, D3D11_GUARD, D3D12_GUARD, WIN32_GUARD})
GUARD_ORDER = (D3D11_GUARD, D3D12_GUARD, METAL_GUARD, WIN32_GUARD, TIMESPEC_GUARD)

WRAPPED_HANDLES = {
    "XrInstance":  ("wine_instance_from_handle",  "host_instance"),
    "XrSession":   ("wine_session_from_handle",   "host_session"),
    "XrSwapchain": ("wine_swapchain_from_handle", "host_swapchain"),
}

EVENT_BASE_STRUCT = "XrEventDataBaseHeader"

REGISTRY_CORE_FEATURES = {"XR_VERSION_1_0": 0, "XR_VERSION_1_1": 1}


@dataclass(frozen=True)
class XrParameter:
    type_name: str
    name: str
    is_const: bool
    is_struct: bool
    pointer: str
    is_array: bool

    @classmethod
    def from_xml(cls, element):
        type_element = element.find("type")
        name_element = element.find("name")
        return cls(type_name=type_element.text,
                   name=name_element.text,
                   is_const=bool(element.text and "const" in element.text),
                   is_struct=bool(element.text and "struct" in element.text),
                   pointer=(type_element.tail or "").strip(),
                   is_array=(name_element.tail or "").strip().startswith("["))

    @property
    def is_wrapped_handle(self):
        return self.type_name in WRAPPED_HANDLES and not self.pointer

    def c_type(self):
        parts = []
        if self.is_const:
            parts.append("const")
        if self.is_struct:
            parts.append("struct")
        parts.append(self.type_name)
        if self.pointer:
            parts.append(self.pointer)
        declaration = " ".join(parts)
        if self.is_array:
            declaration += " *"
        return declaration

    def struct_field(self):
        return f"    {self.c_type()} {self.name};"

    def unix_call_argument(self):
        if self.is_wrapped_handle:
            accessor, host_field = WRAPPED_HANDLES[self.type_name]
            return f"{accessor}(params->{self.name})->{host_field}"
        return f"params->{self.name}"


@dataclass
class XrCommand:
    name: str
    return_type: str
    parameters: list
    alias_target: str = None

    @classmethod
    def from_xml(cls, element):
        prototype = element.find("proto")
        return cls(prototype.find("name").text, prototype.find("type").text,
                   [XrParameter.from_xml(parameter) for parameter in element.findall("param")])

    def aliased_as(self, alias_name):
        return XrCommand(alias_name, self.return_type, self.parameters,
                         alias_target=self.name)


@dataclass
class Registry:
    commands: dict
    types: dict
    extensions: dict
    command_extension: dict
    command_core_minor: dict
    event_structs: list

    @classmethod
    def from_xml(cls, xml_path):
        root = ET.parse(xml_path).getroot()

        types = {}
        for type_element in root.findall("./types/type"):
            name = type_element.get("name") or type_element.find("name").text
            members = []
            structure_type = None
            if type_element.get("category") in ("struct", "union") and not type_element.get("alias"):
                for member in type_element.findall("member"):
                    member_type = member.find("type")
                    member_name = member.find("name")
                    members.append((member_type.text, member_name.text))
                    if member_name.text == "type" and member.get("values"):
                        structure_type = member.get("values")
            structextends = type_element.get("structextends")
            types[name] = {
                "category": type_element.get("category"),
                "requires": type_element.get("requires"),
                "alias": type_element.get("alias"),
                "members": members,
                "parentstruct": type_element.get("parentstruct"),
                "structextends": structextends.split(",") if structextends else [],
                "structure_type": structure_type,
            }

        commands = {}
        deferred_aliases = []
        for command_element in root.findall("./commands/command"):
            alias_target = command_element.get("alias")
            if alias_target:
                deferred_aliases.append((command_element.get("name"), alias_target))
                continue
            command = XrCommand.from_xml(command_element)
            commands[command.name] = command
        for alias_name, target_name in deferred_aliases:
            commands[alias_name] = commands[target_name].aliased_as(alias_name)

        command_core_minor = {}
        for feature in root.findall("feature"):
            minor = REGISTRY_CORE_FEATURES.get(feature.get("name"))
            if minor is None:
                continue
            for require in feature.findall("require"):
                for command in require.findall("command"):
                    command_core_minor[command.get("name")] = minor

        extensions = {}
        command_extension = {}
        for extension in root.findall(".//extensions/extension"):
            if "openxr" not in extension.get("supported", "").split(","):
                continue
            extension_name = extension.get("name")
            command_names = {command.get("name")
                             for require in extension.findall("require")
                             for command in require.findall("command")}
            type_names = {type_element.get("name")
                          for require in extension.findall("require")
                          for type_element in require.findall("type")}
            conditional_requires = [require.get("depends")
                                    for require in extension.findall("require")
                                    if require.get("depends")]
            extensions[extension_name] = {
                "guard": extension.get("protect"),
                "depends": extension.get("depends"),
                "commands": command_names,
                "types": type_names,
                "conditional_requires": conditional_requires,
            }
            for command_name in command_names:
                command_extension.setdefault(command_name, set()).add(extension_name)

        event_structs = []
        for name in sorted(types):
            information = types[name]
            if information["parentstruct"] != EVENT_BASE_STRUCT:
                continue
            for member_type, member_name in information["members"]:
                if member_type in WRAPPED_HANDLES:
                    event_structs.append((name, member_name, member_type))

        return cls(commands=commands, types=types,
                   extensions=extensions, command_extension=command_extension,
                   command_core_minor=command_core_minor, event_structs=event_structs)

    def type_closure(self, root_type_names):
        seen = set()
        stack = list(root_type_names)
        while stack:
            type_name = stack.pop()
            if type_name in seen:
                continue
            seen.add(type_name)
            information = self.types[type_name]
            if information["alias"]:
                stack.append(information["alias"])
            stack.extend(member_type for member_type, _ in information["members"])
        return seen


def depends_satisfiable(expression, satisfied_names):
    atoms = [""]
    operators = []
    depth = 0
    for character in expression:
        if character == "(":
            depth += 1
        elif character == ")":
            depth -= 1
        if character in "+," and depth == 0:
            operators.append(character)
            atoms.append("")
        else:
            atoms[-1] += character

    def atom_satisfiable(atom):
        atom = atom.strip()
        if atom.startswith("("):
            return depends_satisfiable(atom[1:-1], satisfied_names)
        return atom in satisfied_names

    result = atom_satisfiable(atoms[0])
    for operator, atom in zip(operators, atoms[1:]):
        if operator == "+":
            result = result and atom_satisfiable(atom)
        else:
            result = result or atom_satisfiable(atom)
    return result


def group_by_guard(pairs):
    groups = {guard: [] for guard in (None, *GUARD_ORDER)}
    for name, info in pairs:
        groups[info.guard].append((name, info))
    return groups


def emit_guarded(out, groups, emit_entry, prelude=(), blank_after=False):
    for name, info in groups[None]:
        emit_entry(name, info)
    for guard in GUARD_ORDER:
        entries = groups[guard]
        if not entries:
            continue
        out.append(f"#ifdef {guard}")
        out.extend(prelude)
        for name, info in entries:
            emit_entry(name, info)
        out.append(f"#endif /* {guard} */")
        if blank_after:
            out.append("")


@dataclass
class FunctionInfo:
    command: XrCommand
    policy: ThunkPolicy
    guard: str
    extension: str
    core_minor: int
    is_global: bool


@dataclass
class GenerationPlan:
    generated: dict
    extension_rows: list
    session_events: list
    function_rows: list
    unix_slots: list
    dispatch_groups: dict

    @classmethod
    def from_registry(cls, registry):
        generated = {}
        unix_only = {}

        for name in sorted(registry.commands):
            command = registry.commands[name]
            providing = registry.command_extension.get(name, set())
            if len(providing) > 1:
                raise RuntimeError(f"{name} is provided by multiple extensions: "
                                   f"{', '.join(sorted(providing))}")
            extension = next(iter(providing)) if providing else None
            is_core = name in registry.command_core_minor
            if not is_core and extension not in SUPPORTED_EXTENSIONS and name not in FUNCTION_POLICIES:
                continue
            guard = registry.extensions[extension]["guard"] if extension else None
            policy = FUNCTION_POLICIES.get(name, ThunkPolicy())

            info = FunctionInfo(command=command, policy=policy, guard=guard,
                                extension=extension,
                                core_minor=registry.command_core_minor.get(name, 0),
                                is_global=name in GLOBAL_FUNCTIONS)

            if policy.pe is SKIP:
                unix_only[name] = info
                continue
            generated[name] = info

        for name in FUNCTION_POLICIES:
            if name not in generated and name not in unix_only:
                raise RuntimeError(f"FUNCTION_POLICIES entry {name!r} does not match any generated command")

        for name, info in generated.items():
            if info.extension and info.extension not in SUPPORTED_EXTENSIONS:
                raise RuntimeError(f"{name} is provided by {info.extension}, "
                                   f"which is not in SUPPORTED_EXTENSIONS")
            if info.policy.has_unix_call:
                violation = boundary_violation(registry, info.command, info.guard)
                if violation:
                    raise RuntimeError(f"{name} cannot cross the PE/Unix boundary: {violation}")
            if info.command.alias_target:
                target = info.command.alias_target
                if ((target in generated or target in unix_only)
                        and (name in FUNCTION_POLICIES) != (target in FUNCTION_POLICIES)):
                    raise RuntimeError(f"FUNCTION_POLICIES covers only one of alias {name!r} "
                                       f"and target {target!r}")

        for extension_name in sorted(SUPPORTED_EXTENSIONS):
            if extension_name not in registry.extensions:
                raise RuntimeError(f"SUPPORTED_EXTENSIONS references unknown extension {extension_name!r}")
            for command_name in sorted(registry.extensions[extension_name]["commands"]):
                if command_name not in generated:
                    raise RuntimeError(f"{extension_name} is supported but {command_name} is not generated")
            depends = registry.extensions[extension_name]["depends"]
            if depends:
                satisfied = set(SUPPORTED_EXTENSIONS) | set(REGISTRY_CORE_FEATURES)
                if not depends_satisfiable(depends, satisfied):
                    raise RuntimeError(f"{extension_name} dependencies not satisfiable "
                                       f"from SUPPORTED_EXTENSIONS: {depends}")
            conditional_requires = registry.extensions[extension_name]["conditional_requires"]
            if conditional_requires:
                raise RuntimeError(f"{extension_name} has conditional require blocks "
                                   f"the generator does not evaluate: "
                                   f"{', '.join(conditional_requires)}")
            for type_name in sorted(registry.extensions[extension_name]["types"]):
                information = registry.types.get(type_name)
                if not information:
                    continue
                for chain_target in sorted(STRIPPED_NEXT_CHAINS):
                    if chain_target in information["structextends"]:
                        raise RuntimeError(f"{extension_name} chains {type_name} onto "
                                           f"{chain_target}, which the bridge does not forward")

        extension_rows = sorted(SUPPORTED_EXTENSIONS)
        extension_index = {name: index for index, name in enumerate(extension_rows)}

        session_events = []
        for struct_name, member_name, member_type in registry.event_structs:
            owners = {extension_name for extension_name, information in registry.extensions.items()
                      if struct_name in information["types"]}
            if owners and not owners & SUPPORTED_EXTENSIONS:
                continue
            if member_type != "XrSession":
                raise RuntimeError(f"cannot rewrite {member_type} handle in event {struct_name}")
            structure_type = registry.types[struct_name]["structure_type"]
            session_events.append((structure_type, struct_name, member_name))

        function_rows = []
        for name, info in generated.items():
            if info.policy.pe is MANUAL:
                pfn = f"(void *){name}"
            else:
                pfn = f"(void *)wine_{name}"
            if info.extension:
                extension_field = extension_index[info.extension]
                core_minor = 0
            else:
                extension_field = -1
                core_minor = info.core_minor
            function_rows.append((name, pfn, extension_field, core_minor,
                                  1 if info.is_global else 0))
        function_rows.sort(key=lambda row: row[0])

        unix_slots = [("init", "wine_init")]
        unix_slots += [(name, f"wine_{name}") for name in CUSTOM_UNIX_CALLS]
        for name, info in generated.items():
            if not info.policy.has_unix_call:
                continue
            handler = f"wine_{name}" if info.policy.unix is MANUAL else f"thunk_{name}"
            unix_slots.append((name, handler))

        dispatch_groups = group_by_guard((name, info)
                                         for source in (generated, unix_only)
                                         for name, info in source.items()
                                         if info.policy.dispatch)

        return cls(generated=generated,
                   extension_rows=extension_rows,
                   session_events=session_events,
                   function_rows=function_rows, unix_slots=unix_slots,
                   dispatch_groups=dispatch_groups)


def boundary_violation(registry, command, guard):
    if guard not in PE_GUARDS:
        return f"platform guard {guard}"
    closure = registry.type_closure(parameter.type_name for parameter in command.parameters)
    for type_name in sorted(closure):
        information = registry.types[type_name]
        if type_name in UNSUPPORTED_TYPES:
            return f"unsupported type {type_name}"
        if information["category"] == "funcpointer":
            return f"function pointer {type_name}"
        requires = information["requires"]
        if requires and requires not in REGISTRY_SUPPORTED_REQUIRES:
            return f"{type_name} requires {requires}"
    return None


def emit_unixcall_h(plan):
    out = [GENERATED_BANNER]
    out.append("#ifndef __WINE_OPENXR_UNIXCALL_H")
    out.append("#define __WINE_OPENXR_UNIXCALL_H")
    out.append("")
    out.append('#include "openxr/openxr.h"')
    out.append("#include <stdint.h>")
    out.append("")
    out.append("#if !defined(_WINNT_) && !defined(__WINE_WINTERNL_H)")
    out.append("typedef int32_t NTSTATUS;")
    out.append("#endif")
    out.append("")

    out.append("enum unix_call")
    out.append("{")
    for suffix, _handler in plan.unix_slots:
        out.append(f"    unix_{suffix},")
    out.append("    unix_count,")
    out.append("};")
    out.append("")
    out.append(f"#define XR_BRIDGE_EXTENSION_COUNT {len(plan.extension_rows)}")
    out.append("")

    def emit_params(name, info):
        out.append(f"struct {name}_params")
        out.append("{")
        for parameter in info.command.parameters:
            out.append(parameter.struct_field())
        out.append("    XrResult result;")
        for extra_field in info.policy.extra_params:
            out.append(f"    {extra_field}")
        out.append("};")
        out.append("")

    unix_call_groups = group_by_guard((name, info)
                                      for name, info in plan.generated.items()
                                      if info.policy.has_unix_call)
    emit_guarded(out, unix_call_groups, emit_params,
                 prelude=('#include "openxr/openxr_platform.h"', ""),
                 blank_after=True)

    out.append("#endif /* __WINE_OPENXR_UNIXCALL_H */")
    return "\n".join(out) + "\n"


def emit_dispatch_h(plan):
    out = [GENERATED_BANNER]
    out.append("#ifndef __WINE_OPENXR_DISPATCH_H")
    out.append("#define __WINE_OPENXR_DISPATCH_H")
    out.append("")
    out.append("#include <stddef.h>")
    out.append("")

    def slot_line(name, info):
        parameter_types = ", ".join(parameter.c_type()
                                    for parameter in info.command.parameters)
        return f"    {info.command.return_type} (*p_{name})({parameter_types});"

    out.append("struct openxr_instance_funcs")
    out.append("{")
    emit_guarded(out, plan.dispatch_groups,
                 lambda name, info: out.append(slot_line(name, info)))
    out.append("};")
    out.append("")

    out.append("struct openxr_instance_function")
    out.append("{")
    out.append("    const char *name;")
    out.append("    size_t offset;")
    out.append("    const char *extension;")
    out.append("};")
    out.append("")
    out.append("extern const struct openxr_instance_function openxr_instance_functions[];")
    out.append("extern const unsigned int openxr_instance_function_count;")
    out.append("")

    out.append("#endif /* __WINE_OPENXR_DISPATCH_H */")
    return "\n".join(out) + "\n"


def emit_extensions_h(plan):
    out = [GENERATED_BANNER]
    out.append("#ifndef __WINE_OPENXR_EXTENSIONS_H")
    out.append("#define __WINE_OPENXR_EXTENSIONS_H")
    out.append("")
    out.append("static const char *const xr_bridge_extensions[] =")
    out.append("{")
    for name in plan.extension_rows:
        out.append(f'    "{name}",')
    out.append("};")
    out.append("")
    out.append("#endif /* __WINE_OPENXR_EXTENSIONS_H */")
    return "\n".join(out) + "\n"


def emit_events_h(plan):
    out = [GENERATED_BANNER]
    out.append("#ifndef __WINE_OPENXR_EVENTS_H")
    out.append("#define __WINE_OPENXR_EVENTS_H")
    out.append("")
    out.append("#include <stddef.h>")
    out.append('#include "openxr/openxr.h"')
    out.append("")
    out.append("struct xr_session_event")
    out.append("{")
    out.append("    XrStructureType type;")
    out.append("    size_t session_offset;")
    out.append("};")
    out.append("")
    out.append("static const struct xr_session_event xr_session_events[] =")
    out.append("{")
    for structure_type, struct_name, member_name in plan.session_events:
        out.append(f"    {{{structure_type}, offsetof({struct_name}, {member_name})}},")
    out.append("};")
    out.append("")
    out.append("#endif /* __WINE_OPENXR_EVENTS_H */")
    return "\n".join(out) + "\n"


def emit_pe_thunks_c(plan):
    out = [GENERATED_BANNER]
    out.append("")
    out.append("#include <stddef.h>")
    out.append("#include <string.h>")
    out.append("#include <windows.h>")
    out.append("")
    out.append(f"#define {D3D11_GUARD}")
    out.append(f"#define {D3D12_GUARD}")
    out.append(f"#define {WIN32_GUARD}")
    out.append("")
    out.append('#include "bridge.h"')
    out.append('#include "unixcall.h"')
    out.append('#include "extensions.h"')
    out.append("")

    for name, info in plan.generated.items():
        if info.policy.pe is not AUTO:
            continue
        parameter_list = ", ".join(f"{parameter.c_type()} {parameter.name}"
                                   for parameter in info.command.parameters)
        out.append(f"static XrResult WINAPI wine_{name}({parameter_list})")
        out.append("{")
        out.append(f"    struct {name}_params params;")
        out.append("")
        for parameter in info.command.parameters:
            out.append(f"    params.{parameter.name} = {parameter.name};")
        out.append("")
        out.append(f"    UNIX_CALL({name}, &params);")
        out.append("    return params.result;")
        out.append("}")
        out.append("")

    prototypes = []
    for name, info in plan.generated.items():
        if info.policy.pe is not MANUAL or info.extension is None:
            continue
        parameter_list = ", ".join(f"{parameter.c_type()} {parameter.name}"
                                   for parameter in info.command.parameters)
        prototypes.append(f"{info.command.return_type} WINAPI {name}({parameter_list});")
    if prototypes:
        out.extend(prototypes)
        out.append("")

    out.append("static const struct openxr_function xr_function_table[] =")
    out.append("{")
    for name, pfn, extension_field, core_minor, is_global in plan.function_rows:
        out.append(f'    {{"{name}", {pfn}, {extension_field}, {core_minor}, {is_global}}},')
    out.append("};")
    out.append("")

    out.append("const struct openxr_function *wine_xr_find_function(const char *name)")
    out.append("{")
    out.append("    unsigned int low = 0, high = sizeof(xr_function_table) / sizeof(xr_function_table[0]);")
    out.append("    while (low < high)")
    out.append("    {")
    out.append("        unsigned int middle = (low + high) / 2;")
    out.append("        int comparison = strcmp(xr_function_table[middle].name, name);")
    out.append("        if (comparison == 0)")
    out.append("            return &xr_function_table[middle];")
    out.append("        if (comparison < 0)")
    out.append("            low = middle + 1;")
    out.append("        else")
    out.append("            high = middle;")
    out.append("    }")
    out.append("    return NULL;")
    out.append("}")
    out.append("")

    out.append("int wine_xr_extension_index(const char *name)")
    out.append("{")
    out.append("    unsigned int low = 0, high = sizeof(xr_bridge_extensions) / sizeof(xr_bridge_extensions[0]);")
    out.append("    while (low < high)")
    out.append("    {")
    out.append("        unsigned int middle = (low + high) / 2;")
    out.append("        int comparison = strcmp(xr_bridge_extensions[middle], name);")
    out.append("        if (comparison == 0)")
    out.append("            return (int)middle;")
    out.append("        if (comparison < 0)")
    out.append("            low = middle + 1;")
    out.append("        else")
    out.append("            high = middle;")
    out.append("    }")
    out.append("    return -1;")
    out.append("}")
    out.append("")

    return "\n".join(out) + "\n"


def emit_unix_thunks_c(plan):
    out = [GENERATED_BANNER]
    out.append("")
    out.append(f"#define {METAL_GUARD}")
    out.append(f"#define {D3D11_GUARD}")
    out.append(f"#define {D3D12_GUARD}")
    out.append(f"#define {WIN32_GUARD}")
    out.append(f"#define {TIMESPEC_GUARD}")
    out.append("")
    out.append("#include <time.h>")
    out.append("")
    out.append('#include "ntstatus.h"')
    out.append("#define WIN32_NO_STATUS")
    out.append('#include "windef.h"')
    out.append('#include "winnt.h"')
    out.append('#include "winternl.h"')
    out.append('#include "wine/unixlib.h"')
    out.append("")
    out.append('#include "bridge.h"')
    out.append('#include "openxr/openxr_platform.h"')
    out.append('#include "unixcall.h"')
    out.append('#include "dispatch.h"')
    out.append("")
    out.append("extern struct openxr_instance_funcs g_xr_host_instance_dispatch_table;")
    out.append("")

    for suffix, handler in plan.unix_slots:
        if handler.startswith("wine_"):
            out.append(f"extern NTSTATUS {handler}(void *args);")
    out.append("")

    for name, info in plan.generated.items():
        if info.policy.unix is not AUTO:
            continue
        out.append(f"static NTSTATUS thunk_{name}(void *args)")
        out.append("{")
        out.append(f"    struct {name}_params *params = args;")
        out.append("")
        call_arguments = [parameter.unix_call_argument()
                          for parameter in info.command.parameters]
        out.append(f"    params->result = g_xr_host_instance_dispatch_table.p_{name}(")
        for index, argument in enumerate(call_arguments):
            terminator = "," if index < len(call_arguments) - 1 else ");"
            out.append(f"        {argument}{terminator}")
        out.append("")
        out.append("    return STATUS_SUCCESS;")
        out.append("}")
        out.append("")

    def instance_function_line(name, info):
        extension = f'"{info.extension}"' if info.extension else "NULL"
        return (f'    {{"{name}", '
                f"offsetof(struct openxr_instance_funcs, p_{name}), {extension}}},")

    out.append("const struct openxr_instance_function openxr_instance_functions[] =")
    out.append("{")
    emit_guarded(out, plan.dispatch_groups,
                 lambda name, info: out.append(instance_function_line(name, info)))
    out.append("};")
    out.append("")

    out.append("const unsigned int openxr_instance_function_count =")
    out.append("    sizeof(openxr_instance_functions) / sizeof(openxr_instance_functions[0]);")
    out.append("")

    out.append("const unixlib_entry_t __wine_unix_call_funcs[] =")
    out.append("{")
    for _suffix, handler in plan.unix_slots:
        out.append(f"    {handler},")
    out.append("};")
    out.append("")

    out.append("_Static_assert(sizeof(__wine_unix_call_funcs) / sizeof(__wine_unix_call_funcs[0]) == unix_count,")
    out.append('    "Unix call table size mismatch");')
    out.append("")

    return "\n".join(out) + "\n"


def render_all(plan):
    return [
        (UNIXCALL_H, emit_unixcall_h(plan)),
        (DISPATCH_H, emit_dispatch_h(plan)),
        (EXTENSIONS_H, emit_extensions_h(plan)),
        (EVENTS_H, emit_events_h(plan)),
        (PE_THUNKS_C, emit_pe_thunks_c(plan)),
        (UNIX_THUNKS_C, emit_unix_thunks_c(plan)),
    ]


def read_existing(path):
    try:
        with open(path, "r") as handle:
            return handle.read()
    except FileNotFoundError:
        return None


def write_if_changed(path, content):
    if read_existing(path) == content:
        return False
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as handle:
        handle.write(content)
    return True


def check_files(files):
    ok = True
    for path, content in files:
        relative = os.path.relpath(path, PROJECT_DIRECTORY)
        existing = read_existing(path)
        if existing is None:
            print(f"  {relative}: MISSING", file=sys.stderr)
            ok = False
            continue
        if existing == content:
            print(f"  {relative}: ok")
        else:
            print(f"  {relative}: DIFFERS", file=sys.stderr)
            ok = False
    return ok


def main():
    parser = argparse.ArgumentParser(
        description="Generate wineopenxr thunks from the OpenXR registry")
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()

    registry = Registry.from_xml(XR_XML)
    plan = GenerationPlan.from_registry(registry)

    auto_pe = sum(1 for info in plan.generated.values() if info.policy.pe is AUTO)
    manual_pe = len(plan.generated) - auto_pe
    print(f"Parsed {len(registry.commands)} commands, "
          f"generated {auto_pe} auto and {manual_pe} manual thunks, "
          f"{len(plan.session_events)} session events")

    files = render_all(plan)

    if arguments.check:
        if check_files(files):
            print("All generated files are up to date.")
        else:
            print("Generated files are out of date. Run make_openxr.py to regenerate.",
                  file=sys.stderr)
            sys.exit(1)
        return

    for path, content in files:
        relative = os.path.relpath(path, PROJECT_DIRECTORY)
        print(f"  {relative}: {'updated' if write_if_changed(path, content) else 'unchanged'}")


if __name__ == "__main__":
    main()
