/* Generated by make_openxr.py. Do not edit manually */
#ifndef __WINE_OPENXR_EVENTS_H
#define __WINE_OPENXR_EVENTS_H

#include <stddef.h>
#include "openxr/openxr.h"

struct xr_session_event
{
    XrStructureType type;
    size_t session_offset;
};

static const struct xr_session_event xr_session_events[] =
{
    {XR_TYPE_EVENT_DATA_INTERACTION_PROFILE_CHANGED, offsetof(XrEventDataInteractionProfileChanged, session)},
    {XR_TYPE_EVENT_DATA_REFERENCE_SPACE_CHANGE_PENDING, offsetof(XrEventDataReferenceSpaceChangePending, session)},
    {XR_TYPE_EVENT_DATA_SESSION_STATE_CHANGED, offsetof(XrEventDataSessionStateChanged, session)},
    {XR_TYPE_EVENT_DATA_VISIBILITY_MASK_CHANGED_KHR, offsetof(XrEventDataVisibilityMaskChangedKHR, session)},
};

#endif /* __WINE_OPENXR_EVENTS_H */
