/* Generated by make_openxr.py. Do not edit manually */
#ifndef __WINE_OPENXR_EXTENSIONS_H
#define __WINE_OPENXR_EXTENSIONS_H

static const char *const xr_bridge_extensions[] =
{
    "XR_EXT_hand_tracking",
    "XR_FB_display_refresh_rate",
    "XR_KHR_D3D11_enable",
    "XR_KHR_composition_layer_cube",
    "XR_KHR_composition_layer_cylinder",
    "XR_KHR_composition_layer_depth",
    "XR_KHR_composition_layer_equirect",
    "XR_KHR_composition_layer_equirect2",
    "XR_KHR_extended_struct_name_lengths",
    "XR_KHR_locate_spaces",
    "XR_KHR_visibility_mask",
    "XR_KHR_win32_convert_performance_counter_time",
};

#endif /* __WINE_OPENXR_EXTENSIONS_H */
