/* Generated by make_openxr.py. Do not edit manually */
#ifndef __WINE_OPENXR_UNIXCALL_H
#define __WINE_OPENXR_UNIXCALL_H

#include "openxr/openxr.h"
#include <stdint.h>

#if !defined(_WINNT_) && !defined(__WINE_WINTERNL_H)
typedef int32_t NTSTATUS;
#endif

enum unix_call
{
    unix_init,
    unix_create_d3d11_session,
    unix_release_metal_session,
    unix_export_metal_textures,
    unix_xrAcquireSwapchainImage,
    unix_xrApplyHapticFeedback,
    unix_xrAttachSessionActionSets,
    unix_xrBeginFrame,
    unix_xrBeginSession,
    unix_xrConvertTimeToWin32PerformanceCounterKHR,
    unix_xrConvertWin32PerformanceCounterToTimeKHR,
    unix_xrCreateAction,
    unix_xrCreateActionSet,
    unix_xrCreateActionSpace,
    unix_xrCreateHandTrackerEXT,
    unix_xrCreateInstance,
    unix_xrCreateReferenceSpace,
    unix_xrCreateSession,
    unix_xrCreateSwapchain,
    unix_xrDestroyAction,
    unix_xrDestroyActionSet,
    unix_xrDestroyHandTrackerEXT,
    unix_xrDestroyInstance,
    unix_xrDestroySession,
    unix_xrDestroySpace,
    unix_xrDestroySwapchain,
    unix_xrEndFrame,
    unix_xrEndSession,
    unix_xrEnumerateBoundSourcesForAction,
    unix_xrEnumerateDisplayRefreshRatesFB,
    unix_xrEnumerateEnvironmentBlendModes,
    unix_xrEnumerateInstanceExtensionProperties,
    unix_xrEnumerateReferenceSpaces,
    unix_xrEnumerateSwapchainFormats,
    unix_xrEnumerateSwapchainImages,
    unix_xrEnumerateViewConfigurationViews,
    unix_xrEnumerateViewConfigurations,
    unix_xrGetActionStateBoolean,
    unix_xrGetActionStateFloat,
    unix_xrGetActionStatePose,
    unix_xrGetActionStateVector2f,
    unix_xrGetCurrentInteractionProfile,
    unix_xrGetD3D11GraphicsRequirementsKHR,
    unix_xrGetDisplayRefreshRateFB,
    unix_xrGetInputSourceLocalizedName,
    unix_xrGetInstanceProperties,
    unix_xrGetReferenceSpaceBoundsRect,
    unix_xrGetSystem,
    unix_xrGetSystemProperties,
    unix_xrGetViewConfigurationProperties,
    unix_xrGetVisibilityMaskKHR,
    unix_xrLocateHandJointsEXT,
    unix_xrLocateSpace,
    unix_xrLocateSpaces,
    unix_xrLocateSpacesKHR,
    unix_xrLocateViews,
    unix_xrPathToString,
    unix_xrPollEvent,
    unix_xrReleaseSwapchainImage,
    unix_xrRequestDisplayRefreshRateFB,
    unix_xrRequestExitSession,
    unix_xrResultToString,
    unix_xrStopHapticFeedback,
    unix_xrStringToPath,
    unix_xrStructureTypeToString,
    unix_xrStructureTypeToString2KHR,
    unix_xrSuggestInteractionProfileBindings,
    unix_xrSyncActions,
    unix_xrWaitFrame,
    unix_xrWaitSwapchainImage,
    unix_count,
};

#define XR_BRIDGE_EXTENSION_COUNT 12

struct xrAcquireSwapchainImage_params
{
    XrSwapchain swapchain;
    const XrSwapchainImageAcquireInfo * acquireInfo;
    uint32_t * index;
    XrResult result;
};

struct xrApplyHapticFeedback_params
{
    XrSession session;
    const XrHapticActionInfo * hapticActionInfo;
    const XrHapticBaseHeader * hapticFeedback;
    XrResult result;
};

struct xrAttachSessionActionSets_params
{
    XrSession session;
    const XrSessionActionSetsAttachInfo * attachInfo;
    XrResult result;
};

struct xrBeginFrame_params
{
    XrSession session;
    const XrFrameBeginInfo * frameBeginInfo;
    XrResult result;
};

struct xrBeginSession_params
{
    XrSession session;
    const XrSessionBeginInfo * beginInfo;
    XrResult result;
};

struct xrCreateAction_params
{
    XrActionSet actionSet;
    const XrActionCreateInfo * createInfo;
    XrAction * action;
    XrResult result;
};

struct xrCreateActionSet_params
{
    XrInstance instance;
    const XrActionSetCreateInfo * createInfo;
    XrActionSet * actionSet;
    XrResult result;
};

struct xrCreateActionSpace_params
{
    XrSession session;
    const XrActionSpaceCreateInfo * createInfo;
    XrSpace * space;
    XrResult result;
};

struct xrCreateHandTrackerEXT_params
{
    XrSession session;
    const XrHandTrackerCreateInfoEXT * createInfo;
    XrHandTrackerEXT * handTracker;
    XrResult result;
};

struct xrCreateInstance_params
{
    const XrInstanceCreateInfo * createInfo;
    XrInstance * instance;
    XrResult result;
};

struct xrCreateReferenceSpace_params
{
    XrSession session;
    const XrReferenceSpaceCreateInfo * createInfo;
    XrSpace * space;
    XrResult result;
};

struct xrCreateSession_params
{
    XrInstance instance;
    const XrSessionCreateInfo * createInfo;
    XrSession * session;
    XrResult result;
};

struct xrCreateSwapchain_params
{
    XrSession session;
    const XrSwapchainCreateInfo * createInfo;
    XrSwapchain * swapchain;
    XrResult result;
};

struct xrDestroyAction_params
{
    XrAction action;
    XrResult result;
};

struct xrDestroyActionSet_params
{
    XrActionSet actionSet;
    XrResult result;
};

struct xrDestroyHandTrackerEXT_params
{
    XrHandTrackerEXT handTracker;
    XrResult result;
};

struct xrDestroyInstance_params
{
    XrInstance instance;
    XrResult result;
};

struct xrDestroySession_params
{
    XrSession session;
    XrResult result;
};

struct xrDestroySpace_params
{
    XrSpace space;
    XrResult result;
};

struct xrDestroySwapchain_params
{
    XrSwapchain swapchain;
    XrResult result;
};

struct xrEndFrame_params
{
    XrSession session;
    const XrFrameEndInfo * frameEndInfo;
    XrResult result;
    uint64_t gpu_fence_value;
    uint64_t mtl_shared_event;
};

struct xrEndSession_params
{
    XrSession session;
    XrResult result;
};

struct xrEnumerateBoundSourcesForAction_params
{
    XrSession session;
    const XrBoundSourcesForActionEnumerateInfo * enumerateInfo;
    uint32_t sourceCapacityInput;
    uint32_t * sourceCountOutput;
    XrPath * sources;
    XrResult result;
};

struct xrEnumerateDisplayRefreshRatesFB_params
{
    XrSession session;
    uint32_t displayRefreshRateCapacityInput;
    uint32_t * displayRefreshRateCountOutput;
    float * displayRefreshRates;
    XrResult result;
};

struct xrEnumerateEnvironmentBlendModes_params
{
    XrInstance instance;
    XrSystemId systemId;
    XrViewConfigurationType viewConfigurationType;
    uint32_t environmentBlendModeCapacityInput;
    uint32_t * environmentBlendModeCountOutput;
    XrEnvironmentBlendMode * environmentBlendModes;
    XrResult result;
};

struct xrEnumerateInstanceExtensionProperties_params
{
    const char * layerName;
    uint32_t propertyCapacityInput;
    uint32_t * propertyCountOutput;
    XrExtensionProperties * properties;
    XrResult result;
};

struct xrEnumerateReferenceSpaces_params
{
    XrSession session;
    uint32_t spaceCapacityInput;
    uint32_t * spaceCountOutput;
    XrReferenceSpaceType * spaces;
    XrResult result;
};

struct xrEnumerateSwapchainFormats_params
{
    XrSession session;
    uint32_t formatCapacityInput;
    uint32_t * formatCountOutput;
    int64_t * formats;
    XrResult result;
};

struct xrEnumerateSwapchainImages_params
{
    XrSwapchain swapchain;
    uint32_t imageCapacityInput;
    uint32_t * imageCountOutput;
    XrSwapchainImageBaseHeader * images;
    XrResult result;
};

struct xrEnumerateViewConfigurationViews_params
{
    XrInstance instance;
    XrSystemId systemId;
    XrViewConfigurationType viewConfigurationType;
    uint32_t viewCapacityInput;
    uint32_t * viewCountOutput;
    XrViewConfigurationView * views;
    XrResult result;
};

struct xrEnumerateViewConfigurations_params
{
    XrInstance instance;
    XrSystemId systemId;
    uint32_t viewConfigurationTypeCapacityInput;
    uint32_t * viewConfigurationTypeCountOutput;
    XrViewConfigurationType * viewConfigurationTypes;
    XrResult result;
};

struct xrGetActionStateBoolean_params
{
    XrSession session;
    const XrActionStateGetInfo * getInfo;
    XrActionStateBoolean * state;
    XrResult result;
};

struct xrGetActionStateFloat_params
{
    XrSession session;
    const XrActionStateGetInfo * getInfo;
    XrActionStateFloat * state;
    XrResult result;
};

struct xrGetActionStatePose_params
{
    XrSession session;
    const XrActionStateGetInfo * getInfo;
    XrActionStatePose * state;
    XrResult result;
};

struct xrGetActionStateVector2f_params
{
    XrSession session;
    const XrActionStateGetInfo * getInfo;
    XrActionStateVector2f * state;
    XrResult result;
};

struct xrGetCurrentInteractionProfile_params
{
    XrSession session;
    XrPath topLevelUserPath;
    XrInteractionProfileState * interactionProfile;
    XrResult result;
};

struct xrGetDisplayRefreshRateFB_params
{
    XrSession session;
    float * displayRefreshRate;
    XrResult result;
};

struct xrGetInputSourceLocalizedName_params
{
    XrSession session;
    const XrInputSourceLocalizedNameGetInfo * getInfo;
    uint32_t bufferCapacityInput;
    uint32_t * bufferCountOutput;
    char * buffer;
    XrResult result;
};

struct xrGetInstanceProperties_params
{
    XrInstance instance;
    XrInstanceProperties * instanceProperties;
    XrResult result;
};

struct xrGetReferenceSpaceBoundsRect_params
{
    XrSession session;
    XrReferenceSpaceType referenceSpaceType;
    XrExtent2Df * bounds;
    XrResult result;
};

struct xrGetSystem_params
{
    XrInstance instance;
    const XrSystemGetInfo * getInfo;
    XrSystemId * systemId;
    XrResult result;
};

struct xrGetSystemProperties_params
{
    XrInstance instance;
    XrSystemId systemId;
    XrSystemProperties * properties;
    XrResult result;
};

struct xrGetViewConfigurationProperties_params
{
    XrInstance instance;
    XrSystemId systemId;
    XrViewConfigurationType viewConfigurationType;
    XrViewConfigurationProperties * configurationProperties;
    XrResult result;
};

struct xrGetVisibilityMaskKHR_params
{
    XrSession session;
    XrViewConfigurationType viewConfigurationType;
    uint32_t viewIndex;
    XrVisibilityMaskTypeKHR visibilityMaskType;
    XrVisibilityMaskKHR * visibilityMask;
    XrResult result;
};

struct xrLocateHandJointsEXT_params
{
    XrHandTrackerEXT handTracker;
    const XrHandJointsLocateInfoEXT * locateInfo;
    XrHandJointLocationsEXT * locations;
    XrResult result;
};

struct xrLocateSpace_params
{
    XrSpace space;
    XrSpace baseSpace;
    XrTime time;
    XrSpaceLocation * location;
    XrResult result;
};

struct xrLocateSpaces_params
{
    XrSession session;
    const XrSpacesLocateInfo * locateInfo;
    XrSpaceLocations * spaceLocations;
    XrResult result;
};

struct xrLocateSpacesKHR_params
{
    XrSession session;
    const XrSpacesLocateInfo * locateInfo;
    XrSpaceLocations * spaceLocations;
    XrResult result;
};

struct xrLocateViews_params
{
    XrSession session;
    const XrViewLocateInfo * viewLocateInfo;
    XrViewState * viewState;
    uint32_t viewCapacityInput;
    uint32_t * viewCountOutput;
    XrView * views;
    XrResult result;
};

struct xrPathToString_params
{
    XrInstance instance;
    XrPath path;
    uint32_t bufferCapacityInput;
    uint32_t * bufferCountOutput;
    char * buffer;
    XrResult result;
};

struct xrPollEvent_params
{
    XrInstance instance;
    XrEventDataBuffer * eventData;
    XrResult result;
};

struct xrReleaseSwapchainImage_params
{
    XrSwapchain swapchain;
    const XrSwapchainImageReleaseInfo * releaseInfo;
    XrResult result;
};

struct xrRequestDisplayRefreshRateFB_params
{
    XrSession session;
    float displayRefreshRate;
    XrResult result;
};

struct xrRequestExitSession_params
{
    XrSession session;
    XrResult result;
};

struct xrResultToString_params
{
    XrInstance instance;
    XrResult value;
    char * buffer;
    XrResult result;
};

struct xrStopHapticFeedback_params
{
    XrSession session;
    const XrHapticActionInfo * hapticActionInfo;
    XrResult result;
};

struct xrStringToPath_params
{
    XrInstance instance;
    const char * pathString;
    XrPath * path;
    XrResult result;
};

struct xrStructureTypeToString_params
{
    XrInstance instance;
    XrStructureType value;
    char * buffer;
    XrResult result;
};

struct xrStructureTypeToString2KHR_params
{
    XrInstance instance;
    XrStructureType value;
    char * buffer;
    XrResult result;
};

struct xrSuggestInteractionProfileBindings_params
{
    XrInstance instance;
    const XrInteractionProfileSuggestedBinding * suggestedBindings;
    XrResult result;
};

struct xrSyncActions_params
{
    XrSession session;
    const XrActionsSyncInfo * syncInfo;
    XrResult result;
};

struct xrWaitFrame_params
{
    XrSession session;
    const XrFrameWaitInfo * frameWaitInfo;
    XrFrameState * frameState;
    XrResult result;
};

struct xrWaitSwapchainImage_params
{
    XrSwapchain swapchain;
    const XrSwapchainImageWaitInfo * waitInfo;
    XrResult result;
};

#ifdef XR_USE_GRAPHICS_API_D3D11
#include "openxr/openxr_platform.h"

struct xrGetD3D11GraphicsRequirementsKHR_params
{
    XrInstance instance;
    XrSystemId systemId;
    XrGraphicsRequirementsD3D11KHR * graphicsRequirements;
    XrResult result;
};

#endif /* XR_USE_GRAPHICS_API_D3D11 */

#ifdef XR_USE_PLATFORM_WIN32
#include "openxr/openxr_platform.h"

struct xrConvertTimeToWin32PerformanceCounterKHR_params
{
    XrInstance instance;
    XrTime time;
    LARGE_INTEGER * performanceCounter;
    XrResult result;
};

struct xrConvertWin32PerformanceCounterToTimeKHR_params
{
    XrInstance instance;
    const LARGE_INTEGER * performanceCounter;
    XrTime * time;
    XrResult result;
};

#endif /* XR_USE_PLATFORM_WIN32 */

#endif /* __WINE_OPENXR_UNIXCALL_H */
